version: '3.8'

services:
  # Backend FastAPI service
  backend:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../data:/app/data
    environment:
      - LLM_PROVIDER=ollama
      - LLM_MODEL=gemma:7b
      - OLLAMA_URL=http://host.docker.internal:11434
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
    restart: unless-stopped

  # Frontend React service
  frontend:
    build:
      context: ..
      dockerfile: frontend/Dockerfile
    ports:
      - "3002:80"
    depends_on:
      - backend
    restart: unless-stopped